
export const API_ENDPOINT = 'https://script.google.com/macros/s/AKfycbxzKxW5-UqzED89Q_fKcbuFJSIWtAQrcM5b8KGSkpm4VSg-JSgZJkSIj_SdoKe2fDtRGA/exec';

export const INITIAL_RECORD: any = {
  record_id: '',
  created_at: '',
  code_day: '',
  label_day: '',
  mosque_code: '',
  المسجد: '',
  تاريخ_هجري: '',
  عدد_المصلين_رجال: 0,
  عدد_المصلين_نساء: 0,
  عدد_وجبات_افطار: 0,
  عدد_كراتين_ماء: 0,
  عدد_مستفيدي_الضيافة: 0,
  عدد_طلاب_الحلقات: 0,
  عدد_الاوجه_طلاب: 0,
  عدد_طالبات_الحلقات: 0,
  عدد_الاوجه_طالبات: 0,
  عدد_المتطوعين: 0,
  عدد_المسابقات: 0,
  عدد_اطفال_الحضانة: 0,
  عدد_الكلمات_الرجالية: 0,
  عدد_الكلمات_النسائية: 0,
  عدد_مستفيدي_الكلمات: 0,
  عدد_المعتكفين_رجال: 0,
  عدد_المعتكفين_نساء: 0,
  ملاحظات: '',
};
